---
title: "CRPS mapping"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
    theme: readable
    highlight: tango
    toc: yes
    toc_float: yes
    number_section: yes
---


```{r setup, include = FALSE}
# analysis script prepared by Vladimir Aron (Institute of Neuroscience, UCLouvain; vladimir.aron@uclouvain.be) on 20240410

library(ggtext) # extension ggplot
library(glue) # package with extended paste functionnalities
library(ggplot2) # data visualisation package
library(tidyverse)
library(ftExtra)
library(officedown)
library(officer)
library(rvg)
library(patchwork)
library(readxl)
library(writexl)
library(flextable)
library(grid)
library(ggpubr)
library(ggsci)


knitr::opts_chunk$set( # defining default parameters for html document
  tidy    = TRUE,
  warning = FALSE,
  message = FALSE, 
  echo = FALSE,
  comment = FALSE,
  fig.align = "defaut",
  fig.width = 8,
  fig.asp = 0.62,
  out.width = "100%"
  )

flextable::set_flextable_defaults( # defining default for tables output
  font.size = 12, font.family = "Helvetica",
  font.color = "#333333",
  table.layout = "autofit",
  border.color = "gray",
  padding.top = 4, padding.bottom = 4,
  padding.left = 4, padding.right = 4,
  footnote_properties = list(
    font.size = 8  # Set the font size to 8
  )
)

```

```{r functions}
# defines line parameters in tables
dash_border <- fp_border(color = "gray", style = "dashed")
# function used to log tranform
log_qst <- function(x){
  x <- abs(x)
  #x <- x+0.1
  log10(x)
}

ci_low <- function(x){ # function to create lower bound of confidence intervals 95 %
  x <- x[! is.na(x)]
  avg <- mean(x, na.rm = TRUE)
  sd <- sd(x, na.rm = TRUE)
  n <- length(x)
  error <- qnorm(0.95) * sd/sqrt(n)
  avg - error
}

ci_high <- function(x){  # function to create upper bound of confidence intervals 95 %
  x <- x[! is.na(x)]
  avg <- mean(x)
  sd <- sd(x)
  n <- length(x)
  error <- qnorm(0.95) * sd/sqrt(n)
  avg + error
}

# this is a function that will take the side (affected vs. non-affected) and the data set as arguments
# it will output the data set filtered by site and grouped by qst_modality, extremity, sex, and provide mean and SD values
fun_sum <- function(data, s, age_category = 0){
  if(age_category == "2") {
    data_set <- data |> filter(redcap_event_code == "1", side == s) |> 
    select(qst_modality, extremity, sex, values, age_cat_2) |> 
    group_by(qst_modality, extremity, sex, age_cat_2)|> 
    summarize(
      m = mean(values, na.rm = TRUE),
      s = sd(values, na.rm = TRUE),
      sem = (sd(values, na.rm = T))/sqrt(length(values)),
      ci_l = ci_low(values),
      ci_h = ci_high(values)
                     ) 
  cat("\n data set grouped extremity, sex, and  age_cat_2 + filtered by side: ", s,"\n" )
  }else if(age_category == "1"){
    data_set <- data |> filter(redcap_event_code == "1", side == s) |> 
    select(qst_modality, extremity, sex, values, age_cat) |> 
    group_by(qst_modality, extremity, sex, age_cat)|> 
    summarize(
      m = mean(values, na.rm = TRUE),
      s = sd(values, na.rm = TRUE),
      sem = (sd(values, na.rm = T))/sqrt(length(values)),
      ci_l = ci_low(values),
      ci_h = ci_high(values)
                     )
  cat("\n data set grouped extremity, sex, and  age_cat + filtered by side: ", s,"\n" ) 
  } else{
    data_set <- data |> filter(redcap_event_code == "1", side == s) |> 
    select(qst_modality, extremity, sex, values) |> 
    group_by(qst_modality, extremity, sex)|> 
    summarize(
      m = mean(values, na.rm = TRUE),
      s = sd(values, na.rm = TRUE),
      sem = (sd(values, na.rm = T))/sqrt(length(values)),
      ci_l = ci_low(values),
      ci_h = ci_high(values)
                     ) 
  cat("\n data set grouped extremity and sex + filtered by side: ", s,"\n" ) 
  }
  return(data_set)
}




my_theme_2 <- function(base_size = 9, # defining graphical parameters for ggplots
                     base_family = 'Arial',
                     base_line_size = base_size/22,
                     base_rect_size = base_size/22,
                    border = FALSE) {
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        axis.line.x = element_line(colour = "grey50"),
        axis.line.y = element_line(colour = "grey50"),
        panel.background = element_blank(), 
        plot.title = element_markdown(hjust = .5),
        plot.caption = element_markdown(hjust = 1.2, size = 7),
        axis.title.x = element_text(margin = margin(t = 20)))
}

```

```{r data_load}
# new names for data set columns
new_names_qst <- c("cdt_control" = "cdt" ,  "wdt_control" = "wdt", "tsl_control" = "tsl" , "phs_control" ="psh" , "cpt_control" = "cpt", "hpt_control" = "hpt", "mdt_control" = "mdt","mpt_control"= "mpt", "mps_control" = "mps", "dma_control" = "dma", "wur_control" = "wur","vdt_control" = "vdt" , "ppt_control" = "ppt", "phs_affected" = "psl_affected")

    
data <- read_xlsx("../data/mh_data_20240307.xlsx") |>  # importing data from .xlsx file
  rename(all_of(new_names_qst)) %>% # renaming
  mutate(age_cat = case_when( # creating age categories based on Magerl 2010 normative values
    age >= 20 & age < 30 ~ "1",
    age >= 30 & age < 40 ~ "2",
    age >= 40 & age < 50 ~ "3",
    age >= 50 & age < 60 ~ "4",
    age >= 60 ~ "5"
  ),
  age_cat_2 = if_else(age <40, "<40", "≥40"), # creating age category normative values
  extremity = if_else(area_qst %in% c("1","3","4","5"), "UE","LE") # various locations are classified as upper or lower limb
  ) |> 
  mutate(age_cat = factor(age_cat),
         area_qst = factor(area_qst, levels = c("1","2","3","4","5","6"),
                           labels = c("hand", "foot", "wrist palmar", "hand palmar", "elbow", "knee")), 
         sex = factor(sex, levels = c("1", "2"), labels = c("f", "h"))) |>  # vérifier label sex !!!
           select(! c(ppt_aff_zscore, wdt_aff_log_z))




norm <- read_xlsx("../data/norms_sdrc_20240307.xlsx") # importing normative values


data_norm <- norm |> pivot_longer(cols = starts_with(c("h",  "f")),
                                  names_to = c("sex", "metrics", "age_cat"),
                                  names_sep = "_",
                                  values_to = c("value")) |> 
  pivot_wider(names_from = "metrics",
              values_from = "value") |> 
  mutate(age_cat = factor(age_cat)) |>  rename("qst_modality" = "test_mod", "area_qst" = "site") |> # normative values areas are categorized according to extremity
  mutate(extremity = if_else(area_qst == "foot", "LE", "UE")) |> 
  select(!area_qst)



  

# replacing DMA values = 0.1 by 0
data$dma_affected[data$dma_affected == 0.1] <- 0
data$dma_control[data$dma_control == 0.1] <- 0


```

```{r log_T }

# set of all qst
qst_set <- c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt")
# set of qst to be log transormed
qst_log <- qst_set[!qst_set %in% c("hpt", "cpt", "phs","vdt", "dma")]

data_log <- data %>% mutate(across(starts_with(qst_log), log_qst )) # log transforming data

data_tab_log <- data_log |>  # long format of logT data + selecting grouping variables
  select(patient_id,redcap_event_code, age_cat,age_cat_2, area_qst,extremity, sex, starts_with(qst_set)) |> 
  pivot_longer(
    cols = starts_with(c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt")),
    names_to = c("qst_modality", "side"),
    names_pattern = "(^\\w+)_(\\w+)",
    values_to = "values"
                         ) |> 
  mutate(qst_modality = factor(qst_modality,levels = c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt"),labels = c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt"))) |> na.omit()




data_tab_nolog <- data  |>  # long format of raw data + selecting grouping variables
  select(patient_id,redcap_event_code, age_cat,age_cat_2, area_qst,extremity, sex, starts_with(qst_set)) |> 
  pivot_longer(
    cols = starts_with(c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt")),
    names_to = c("qst_modality", "side"),
    names_pattern = "(^\\w+)_(\\w+)",
    values_to = "values"
                         ) |> 
  mutate(qst_modality = factor(qst_modality,levels = c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt"),labels = c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt"))) |> na.omit()






  

```

# Table 1

```{r table_1}
fun_t1  <- function(dl, a = 0){ 
  # table creating function
  # input: dl, dataset; a, refers to age category--- fun_sum above
  # output: formatted table for QST data according to sex and extremity

# Separating the data set for affected and control limbs with non logT data
 
  sum_raw_aff <- fun_sum(data = dl, s = "affected", age = a) # fun_sum, see function above


  #reformatting the data set in table ready format
  t_raw_aff <- sum_raw_aff |> 
  mutate(across(where(is.numeric), round, 1)) |> 
    mutate(ms = glue("{m} ± {s}")) |> 
    select(! c(m, s, sem, ci_l, ci_h)) |> 
    pivot_wider(names_from = c(extremity, sex), values_from = ms) |> 
    mutate(qst_modality = toupper(qst_modality)) |> 
    select(qst_modality, "UE_f", "UE_h", "LE_f","LE_h" ) 

  # building the table
 
  table1 <- t_raw_aff |> 
    flextable() |> 
    autofit() |> 
    theme_vanilla() |> 
    set_header_labels(
    qst_modality = "QST modalities", 
                    "UE_f" = "Females \n (n = 38)", 
    "UE_h" = "Males \n (n = 10)",
    "LE_f" = "Females \n (n = 25)", 
    "LE_h" = "Males \n (n = 6)"
                    ) |> 
      add_header_row(
    values = c("QST modalities", "Upper Extremity", "Lower Extremity"),
    colwidths = c(1,2,2) ) |>
  merge_v(part = "header", j = 1) |> 
  align(part = "header", align = "center") |> 
  align(part = "body", align = "center")
  table1 <- vline(table1, j = 1, part = "all", border = dash_border)
  table1 <- table1 |> 
   add_footer_lines(
    values = "Mean ± SD. Abbreviations: CDT, Cold detection threshold; WDT, Warm detection threshold; TSL, Thermal sensory limen; PHS, Paradoxical heat sensation; CPT, Cold pain threshold; HPT, Heat pain threshold; MDT, Mechanical detection threshold; MPT, Mechanical pain threshold; MPS, Mechanical pain sensitivity; DMA, Dynamic mechanical allodynia; WUR, Wind-up ratio; VDT, Vibration detection threshold; PPT, Pressure pain threshold."
                   )
  return(table1)
}

table1_log <- fun_t1(dl = data_tab_log) # creating table for logT data
table1_log

#save_as_docx( # saving as .docx document
  #"table 1 log" = table1_log,  
 # path = "../output/table_1_log.docx")
```

# Table 2

```{r z_database}

# Z-scores ($\overline{x} ± {SD}$) for each QST modality (except PHS and DMA) using the following formula: $$z_i = \frac{x_{\text{aff},i} - \overline{x}_\text{cont}}{SD_\text{cont}}$$

# Grouping: age category ($<40$ vs $≥40$), extremity and sex


sum_raw_cont <- fun_sum(data = data_tab_log, s = "control", age = 2) |> # contraletral summary of QST grouping by age_cat_2, sex, and extremity in logT data
  mutate(s = if_else(s == "0",1, s)) # null standard deviation are replaced by 1


data_log_aff <-  data_tab_log |> filter(redcap_event_code == "1")  |> # selecting logT data for the affected side
  #filter(patient_id != "223") |> 
  filter(side == "affected") |> na.omit() 


# merging the two data sets
data_db_z <- full_join(data_log_aff, sum_raw_cont) |> 
  group_by(qst_modality, extremity, sex, age_cat_2) |> 
  mutate(z_db = (values - m) / s)  |> 
  mutate(z_db = if_else(qst_modality %in% c("mps", "cpt", "wur","vdt"), z_db, z_db * (-1)))# multiplying z by -1 to adequatly rpz gain and loss of function

#data_db_z$z_db <- data_db_z$z_db*(-1)


# creating the table + summary
m_z <- data_db_z |> 
  group_by(qst_modality) |> 
    summarize(
      m_z = mean(z_db, na.rm = TRUE),
      s_z = sd(z_db, na.rm = TRUE),
      sem_z = (sd(z_db, na.rm = T))/sqrt(length(values)),
      ci_l_z = ci_low(z_db),
      ci_h_z = ci_high(z_db)
                     )  |> 
  filter(qst_modality != "dma", qst_modality != "phs")

colnames(m_z) <- c("qst_modality", "m_z_database", "s_z_database", "sem_z_database", "ci_l_z_database", "ci_h_z_database")
#data_db_z$z_db[which(data_db_z$z_db == "NaN")] <- 0



```


```{r z_norm}

fun_z_norm <- function(x){
  # input : side (affected vs contralat)
  # output: Z-scores contraleral and affected side to the normative values of the logT data while grouping by sex, age categroy, and extremity
  data_full <- full_join(data_tab_log, data_norm) |> select(!cil) # merging normative values and inclusion data set
  data_full_z <- na.omit(data_full)
  
  z_norm <- data_full_z |>  
    filter(redcap_event_code == "1") |> 
    mutate(qst_modality = factor(qst_modality,levels = c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt"),labels = c("cdt", "wdt", "tsl", "phs", "cpt", "hpt", "mdt", "mpt", "mps", "dma", "wur", "vdt", "ppt"))) |> 
    filter(side == x) |> 
  group_by(sex, age_cat, extremity) |> 
  mutate(z = (values - m) / sd) |> 
    mutate(z = if_else(qst_modality %in% c("mps", "cpt", "wur", "vdt"), z, z * (-1)))# multiplying z score by -1 to adequatly rpz gain and loss of function
    
  
  #h <- subset(z_norm, qst_modality == "dma")

  z_norm$z[which(z_norm$z == "NaN")] <- 0
  

   z_table <- z_norm |> 
     group_by(qst_modality) |> 
     summarize(
      m_z_norm = mean(z, na.rm = TRUE),
      s_z_norm = sd(z, na.rm = TRUE),
      sem_z_norm = (sd(z, na.rm = T))/sqrt(length(values)),
      ci_l_z_norm = ci_low(z),
      ci_h_z_norm = ci_high(z)
                     )  |> 
  filter(qst_modality != "dma", qst_modality != "phs")
     
   if(x == "affected"){
     
     colnames(z_table) <- c("qst_modality", "m_z_norm_aff", "s_z_norm_aff", "sem_z_norm_aff", "ci_l_z_norm_aff", "ci_h_z_norm_aff")
   }
   else{
     
     colnames(z_table) <- c("qst_modality", "m_z_norm_cont", "s_z_norm_cont", "sem_z_norm_cont", "ci_l_z_norm_cont", "ci_h_z_norm_cont")
   }

 return(z_table)
}


z_table_norm_aff <- fun_z_norm("affected")

z_table_norm_cont <- fun_z_norm("control")



    

```

```{r table_2}

z_table_full <- cbind(m_z,z_table_norm_aff[,-1],z_table_norm_cont[,-1] ) |> 
  mutate(across(where(is.numeric), round,2)) # grouping z-scores 


n <- data_tab_nolog |>     filter(redcap_event_code == "1", side == "affected") |>
  count(qst_modality) 

z_table_full_n <- full_join(n, z_table_full) # adding number of participants included for each qst_modality to the global z-scores data set

# then we create a function that will determine the t value as per Magerl et al., 2010

fun.t.new <- function(m_z,s_z, n, print_cat = F){
  t <- (m_z - 0)/ sqrt(s_z^2/n + 1/n)
  ddf <- 2*(n - 1)
  p <- 2*pt(q=abs(t), df=ddf, lower.tail = F)
  p <- round(p, 4)
  decision <- if_else(p < 0.05, "RH0", "NRH0")
  
  ci_up <- (m_z+t^2/2)/(n+t^2)
  ci_low <- (m_z-t^2/2)/(n+t^2)
  
   return(p)
  
  if(print_cat == T){
  cat("Difference between means: \n")
  cat("M1 - M2 = ", m_z, " - 0 = ",m_z,"\n" )
  cat("stat t:", t, "\n")
  cat("p val: ", p,"\n")
  cat("Decision: ", decision)
  }


}

# we also create a function to assign a value to the specific p values

fun_p_cat <- function(x){
  if(x < 0.05){
    if(x < 0.05 & x > 0.01){cat <- "<0.05"}
    else if(x < 0.01 & x > 0.001){cat <- "<0.01"}
    else{cat <- "<0.001"}
  } else if(x >= 0.05){
    cat <- as.character(x)
  } else{cat <- "NA"}
  return(cat)
}



# p values are added to the z-score data set

z_table_full_p <- z_table_full_n |>  
  filter(qst_modality != "phs", qst_modality !="dma") |> 
  group_by(qst_modality) |> 
  mutate(
  p_z_db = fun.t.new(m_z_database,s_z_database, n),
  p_z_norm_aff = fun.t.new(m_z_norm_aff,s_z_norm_aff, n),
  p_z_norm_cont = fun.t.new(m_z_norm_cont, s_z_norm_cont,n)
) 

# correcting the p-values for multiple comparions (bonferroni)

z_table_full_p$p_z_db_adj <- p.adjust(z_table_full_p$p_z_db, method = "bonferroni") 
z_table_full_p$p_z_norm_aff_adj <- p.adjust(z_table_full_p$p_z_norm_aff, method = "bonferroni")
z_table_full_p$p_z_norm_cont_adj <- p.adjust(z_table_full_p$p_z_norm_cont, method = "bonferroni")

z_table_full_p <- z_table_full_p |>
  mutate(across(where(is.numeric), round, 2)) |> 
  mutate(
  p_cat_z_db = fun_p_cat(p_z_db),
  p_cat_z_norm_aff = fun_p_cat(p_z_norm_aff),
  p_cat_z_norm_cont = fun_p_cat(p_z_norm_cont),
  p_cat_z_db_adj = fun_p_cat(p_z_db_adj),
  p_cat_z_norm_aff_adj = fun_p_cat(p_z_norm_aff_adj),
  p_cat_z_norm_cont_adj = fun_p_cat(p_z_norm_cont_adj),
  
       ) |>
  mutate(
    p_cat_db = glue("{p_cat_z_db} / {p_cat_z_db_adj}"),
    p_cat_norm_cont = glue("{p_cat_z_norm_cont} / {p_cat_z_norm_cont_adj}"),
    p_cat_norm_aff = glue("{p_cat_z_norm_aff} / {p_cat_z_norm_aff_adj}")
  ) 

# producing table 2: z scores (affected vs contralateral; affected vs norm; contralateral vs norm for each QST_modality)

table2_p <- z_table_full_p |> 
  mutate(z_db = glue("{m_z_database} ± {s_z_database}"),
         z_norm_aff = glue("{m_z_norm_aff} ± {s_z_norm_aff}"),
         z_norm_cont = glue("{m_z_norm_cont} ± {s_z_norm_cont}")
         ) |> 
  select(qst_modality,  z_norm_aff,p_cat_norm_aff, z_norm_cont, p_cat_norm_cont, z_db, p_cat_db,) |> 
  mutate(qst_modality = toupper(qst_modality)) |> 
  flextable() |> 
  theme_vanilla() |> 
  set_header_labels(qst_modality = "QST modalities",
                    z_db = "Affected/contralateral",
                    p_cat_db = "*p* / *p*~corr~",
                    z_norm_aff = "Affected/norm",
                    p_cat_norm_aff = "*p* / *p*~corr~",
                    z_norm_cont = "Contralateral/norm",
                    p_cat_norm_cont = "*p* / *p*~corr~"
                    ) |> autofit() |> 
  colformat_md(j = c(3,5,7), part = "header") |> 
  align(align = "center", part = "all")



table2_p <- vline(table2_p, j = 1, part = "all", border = dash_border) |> 
   add_footer_lines(
    values = "Mean ± SD. Abbreviations: P corr, Corrected P-values using the Bonferroni correction; CDT, Cold detection threshold; WDT, Warm detection threshold; TSL, Thermal sensory limen; PHS, Paradoxical heat sensation; CPT, Cold pain threshold; HPT, Heat pain threshold; MDT, Mechanical detection threshold; MPT, Mechanical pain threshold; MPS, Mechanical pain sensitivity; DMA, Dynamic mechanical allodynia; WUR, Wind-up ratio; VDT, Vibration detection threshold; PPT, Pressure pain threshold."
                   ) 


table2_p 

#save_as_docx( # saving as .docx document
  #"table 2_p" = table2_p,  
 # path = "../output/table_2_p.docx")

```


# Figures: Z-scores for each QST-modality

```{r fig_z}


fig.data <- z_table_full |> # z-score data set is formatted for visualisation (long format)
  pivot_longer(cols = !qst_modality, 
               names_to = c("metrics", "group"),
               names_sep = "_z_",
               values_to = "z") |> 
  mutate(qst_modality = toupper(qst_modality)) |>
    mutate(qst_modality = factor(qst_modality, levels = c("CDT", "WDT", "TSL", "CPT","HPT", "PPT", "MPT", "MPS", "WUR", "MDT", "VDT"))) |> 
  mutate(group = factor(group, levels = c("database", "norm_aff", "norm_cont"), labels = c("Affected vs. Contralateral", "Affected vs. Norm", "Contralateral vs. Norm"))) 

fig.p <- z_table_full_p |> # adding previous data frame the p values
  select(!n) |> 
  pivot_longer(cols = starts_with("p_z") & ends_with("adj"), 
               names_to = c( "group"),
               values_to = "p") |> mutate(qst_modality = toupper(qst_modality)) |>
  select(qst_modality, p, group) |> 
    mutate(qst_modality = factor(qst_modality, levels = c("CDT", "WDT", "TSL", "CPT","HPT", "PPT", "MPT", "MPS", "WUR", "MDT", "VDT"))) |> 
  mutate(group = factor(group, levels = c("p_z_db_adj", "p_z_norm_aff_adj", "p_z_norm_cont_adj"), labels = c("Affected vs. Contralateral", "Affected vs. Norm", "Contralateral vs. Norm"))) 


fig.data.p <- full_join(fig.data, fig.p)


fig_qst <- function(dt, disp = "ci", p = T, type = "n"){
  
# output figure of z-scores for each QST modality
# input: dt, data set; disp, disperison measure to be used: default = CI 95%; p, wether bonferroni adjusted p value should be present: defautl = TRUE; type, comparison type, default = norm comparisons. 

  
  txt_gain <- text_grob(label = "gain of function", size = 9,rot = 90)
  txt_loss <- text_grob(label = "loss of function", size = 9,rot = 90)
  
  fig.data.m <- dt |> filter(metrics == "m")


  fig.data.s <- dt |> 
    filter(metrics %in%c("m","s")) |> 
    pivot_wider(names_from = "metrics",       values_from = "z") |> 
  mutate(low = m-s,
         high = m+s) |>
    mutate(qst_modality = factor(qst_modality, levels = c("CDT", "WDT", "TSL", "CPT","HPT", "PPT", "MPT", "MPS", "WUR", "MDT", "VDT"))) 
  
  fig.data.sem <- dt |> 
    filter(metrics %in%c("m","sem")) |> 
    pivot_wider(names_from = "metrics",       values_from = "z") |> 
  mutate(low = m-sem,
         high = m+sem) |>
    mutate(qst_modality = factor(qst_modality, levels = c("CDT", "WDT", "TSL", "CPT","HPT", "PPT", "MPT", "MPS", "WUR", "MDT", "VDT"))) 
  
  fig.data.ci <- dt |> 
    filter(metrics %in%c("m","ci_l","ci_h")) |> 
    pivot_wider(names_from = "metrics", values_from = "z") |> 
      rename("low" = "ci_l", "high" = "ci_h") |> 
    mutate(qst_modality = factor(qst_modality, levels = c("CDT", "WDT", "TSL", "CPT","HPT", "PPT", "MPT", "MPS", "WUR", "MDT", "VDT"))) 

  
  pos <- position_dodge(width=0.6)
  
  if(disp == "s"){
    fig.data.disp <- fig.data.s
    d <- "SD"
  } else if(disp == "sem"){
    fig.data.disp <- fig.data.sem
    d <- "SEM"
  } else if(disp == "ci"){
    fig.data.disp <- fig.data.ci
    d <- "CI 95%"
  }
  
  if(p == T){
    fig.data.disp <- fig.data.disp |> mutate(p_point = if_else(p<0.05, high + 0.3, 100)) 
  } else{
    fig.data.disp <- fig.data.disp
  }

  d.rect <- data.frame(x1 = 0, x2 = Inf, y1 = -1.96, y2 = 1.96)
  
  
  
  fig_norm <- ggplot() + 
    geom_errorbar(data = fig.data.disp |> filter(group != "Affected vs. Contralateral"), aes(x = qst_modality,  ymin = low, ymax = high, col = group), width = 0.2, position = pos) +
  geom_point(data = fig.data.m |> filter(group != "Affected vs. Contralateral"), aes(x = factor(qst_modality), y = z, col = group, shape = group), size = 3, position = pos) +
  #geom_line(data = fig.data.m, aes(x = factor(qst_modality), y = z,  group = group, linetype = group), alpha = 0.3, position = pos) +
  scale_y_continuous(limits = c(-5,5), breaks = seq(-3,3,1)) +
  geom_hline(yintercept = 0, alpha = 0.7) +
  geom_hline(yintercept = c(-1.96,1.96), alpha = 0.7, linetype = "dashed") +
    geom_rect(data = d.rect, aes(ymin = y1, ymax = y2, xmin = x1, xmax = x2), alpha = 0.2, fill = "lightgrey") +
    scale_color_lancet() +
  labs(
    title = "",
    x = "QST parameter",
    y = "Z-score",
    col = "",
    shape = "",
    linetype = ""
  ) + my_theme_2() +
annotation_custom(txt_loss, xmin  = -1, xmax = 0, ymin = -2.5, ymax = -4.5) +
annotation_custom(txt_gain, xmin  = -1, xmax = 0, ymin = 2.5, ymax = 4.5) +
  coord_cartesian(clip = "off") + 
    theme(legend.position = "bottom")
  
  
  
  
  fig_aff_cont <- ggplot() + 
    geom_errorbar(data = fig.data.disp |> filter(group == "Affected vs. Contralateral"), aes(x = qst_modality,  ymin = low, ymax = high, col = group), width = 0.2, position = pos) +
  geom_point(data = fig.data.m |> filter(group == "Affected vs. Contralateral"), aes(x = factor(qst_modality), y = z, col = group, shape = group), size = 3, position = pos) +
  #geom_line(data = fig.data.m, aes(x = factor(qst_modality), y = z,  group = group, linetype = group), alpha = 0.3, position = pos) +
  scale_y_continuous(limits = c(-5,5), breaks = seq(-3,3,1)) +
  geom_hline(yintercept = 0, alpha = 0.7) +
  geom_hline(yintercept = c(-1.96,1.96), alpha = 0.7, linetype = "dashed") +
    geom_rect(data = d.rect, aes(ymin = y1, ymax = y2, xmin = x1, xmax = x2), alpha = 0.2, fill = "lightgrey") +
    scale_colour_discrete(type = "#42B54099")+
    scale_shape_manual(values = 15) +
  labs(
    #paste("Dispersion measure = ", d)
    x = "QST parameter",
    y = "Z-score",
    col = "",
    shape = "",
    linetype = ""
  ) + my_theme_2() +
annotation_custom(txt_loss, xmin  = -1, xmax = 0, ymin = -2.5, ymax = -4.5) +
annotation_custom(txt_gain, xmin  = -1, xmax = 0, ymin = 2.5, ymax = 4.5) +
  coord_cartesian(clip = "off")+ 
    theme(legend.position = "bottom")
  

  
  if(p == T){
    fig_norm <- fig_norm + 
    geom_point(data = fig.data.disp |> filter(group != "Affected vs. Contralateral"), aes(x = qst_modality, y = p_point, col= group , group = group), shape = 8, position = pos, size = 0.7) 
    
        fig_aff_cont <- fig_aff_cont + 
    geom_point(data = fig.data.disp |> filter(group == "Affected vs. Contralateral") , aes(x = qst_modality, y = p_point, col= group , group = group), shape = 8, position = pos, size = 0.7) 
    
    
  } else{
    fig_norm <- fig_norm
    fig_aff_cont <- fig_aff_cont
  }
  
  if(p == T){
    file_name <- paste("fig3_", disp, "_", "p_", type, ".png", sep ="")
  } else{
      file_name <- paste("fig3_", disp, "_", type, ".png", sep ="")
      }
  
  
  if(type == "n"){
    #ggsave(filename = file_name, plot = fig_norm, path = "../output", dpi = 600)
    return(fig_norm)
  } else {
    #ggsave(filename = file_name, plot = fig_aff_cont, path = "../output", dpi = 600)
      return(fig_aff_cont)
    }
 
}



fig3_norm <- fig_qst(fig.data.p,type =  "n")
fig3_aff <- fig_qst(fig.data.p, type = "aff")



fig3_norm
fig3_aff





```

